### ISSUE TITLE
test code output results and compare vs Python implementation

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/cfd-mini-app#15]
This is to ensure consistency between the 2 implementations.
* create comparative plots along lines across mesh
* create comparative 2D visualizations
for both OoIs (velocity and pressure).

**Comment by pierrepebay** [comment]
Side by side comparaison of x component of velocity across very coarse 10x10 mesh:

<img width="909" alt="Screenshot 2021-08-20 at 14 00 22" src="https://user-images.githubusercontent.com/68857547/130230140-3045a568-d95a-4d38-b6c3-10e3de56a0df.png">

**Comment by ppebay** [comment]
Please provide *all* input parameters in the comment above @pierrepebay

**Comment by pierrepebay** [comment]
Horizontal velocity component values along middle vertical line of mesh (same parameters as comment above) :

![Screenshot 2021-08-20 at 17 32 11](https://user-images.githubusercontent.com/68857547/130257681-2a46f480-ac4a-40f5-8ab0-0a5ff43f28af.png)

**Comment by pierrepebay** [comment]
Same study case, for Re = 100 ceteris paribus.
Oscillation in values is due to high Reynolds number for very coarse mesh.

![Screenshot 2021-08-20 at 19 29 58](https://user-images.githubusercontent.com/68857547/130271637-49ccb8fd-2f46-45d1-8a21-cf74ae798adb.png)

**Comment by ppebay** [comment]
An important _caveat_: the Python implementation uses NumPy's linear solve which itself leverages LAPACK, in contrast to the C++ implementation that uses a home-made naïve CG implementation ("naïve" in the sense that it does not use preconditioning, nor numerical stabilization of the conjugate directions to compensate for round-off errors]. 
Therefore, other than verifying that the current implementation is not producing wildly incorrect results, which should not focus much more on the numerical accuracy at this point, until we use a better kernel for the linear solve.
