### ISSUE TITLE
Make Kokkos::Views 2-dimensional to follow cartesian grid

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/cfd-mini-app#30]
- The velocity could look like `Kokkos::View<double**[2]> velocity;`, as there is a `u` and `v` component to it.
- The pressure would just be `Kokkos::View<double**> pressure;`.

**Comment by ppebay** [comment]
For `pressure` it is probably better for now to keep it as a one-dimensional view, in order to pass it "as-is" to the Kokkos Kernels solver.

The PR corresponding to this issue will thus only focus on the refactoring for `velocity`
